routes/web.php
<?php

use App\Models\ViewModel\RootMenuNode;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    /*
    |-------------------------------------------
    | admin routes
    |--------------------------------------------
    */
    Route::prefix('admin')->namespace('Admin')->group(function () {
        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::get('profile', 'UserController@showProfile')->name('profile');

        Route::get('reset-password', 'ResetPasswordController@edit')->name('user.reset-password');
        Route::put('reset-password', 'ResetPasswordController@update');
    });
    /*
    |-------------------------------------------
    | master routes
    |--------------------------------------------
    */
    Route::prefix('master')->namespace('Master')->group(function () {
        Route::resource('company', 'CompanyController');
        Route::resource('activity', 'ActivityController');
        Route::resource('executivetarget', 'EexecutiveTargetController');
        Route::resource('empinactivity', 'EmpInActivityController');
        Route::resource('strategicplan', 'StrategicPlanController');
        Route::resource('employee', 'EmployeeController');
        Route::resource('adminunit', 'AdminUnitController');

        Route::resource('activityfollowup', 'ActivityFollowUpController');
        Route::resource('targetoutput', 'TargetOutputController');
        Route::resource('admininactivity', 'AdminInCompController');
        Route::resource('tasks', 'TasksController');
        Route::resource('planWeeks', 'MonthWeekController');

        Route::resource('fundingsources', 'FundingSourcesController');

        Route::resource('perfornanceindex', 'PerfornanceIndexController');
        Route::resource('strategictarget', 'StrategicTargetController');
        Route::resource('targetindex', 'TargetIndexController');
        Route::resource('follow', 'FollowActivityExeViewController');

    });
});
Auth::routes(['register' => false]);

app/Models/Master/Activity.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;
use Bitwise\PermissionSeeder\PermissionSeederContract;
use Bitwise\PermissionSeeder\Traits\PermissionSeederTrait;
use App\Traits\HasFilter;


class Activity extends Model implements PermissionSeederContract
{
    use HasFilter;
    protected $table = 'activity';
    protected $guarded = [];
    use PermissionSeederTrait;
    public function getPermissionActions(){
        return config('permission_seeder.actions',[
            'List',
            'Create',
            'Edit',
            'Delete'
        ]);
}
}

app/Models/Master/ActivityEmpAdminView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityEmpAdminView extends Model
{
    protected $table = 'activity_emp_admin_view';
    protected $guarded = [];

  
}

app/Models/Master/ActivityFollowExecutiveView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityFollowExecutiveView extends Model
{
    protected $table = 'activity_follow_executive_view';
    protected $guarded = [];
}

app/Models/Master/ActivityFollowPlanWeeksView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityFollowPlanWeeksView extends Model
{
    protected $table = 'activity_follow_up_plan_weeks_comp_view';
    protected $guarded = [];
}

app/Models/Master/ActivityFollowUp.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityFollowUp extends Model
{
    protected $table = 'activity_follow_up';
    protected $guarded = [];
}

app/Models/Master/ActivityFollowUpView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityFollowUpView extends Model
{
    protected $table = 'activity_follow_up_view';
    protected $guarded = [];
}

app/Models/Master/AddFollowActiveView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class AddFollowActiveView extends Model
{
    protected $table = 'add_follow_active_view1';
    protected $guarded = [];
}

app/Models/Master/AddFollowActiveViewLast.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class AddFollowActiveViewLast extends Model
{
    protected $table = 'add_follow_active_view';
    protected $guarded = [];
}

app/Models/Master/AdminInActivity.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class AdminInActivity extends Model
{
    protected $table = 'admin_in_activity';
    protected $guarded = [];
}

app/Models/Master/AdminUnit.php
<?php

namespace App\Models\Master;
use Illuminate\Support\Facades\Auth;
use App\Traits\HasFilter;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Master\OperationPlane;

class AdminUnit extends Model

    {
        protected $table = 'admin_unit';
        protected $guarded = [];
        use HasFilter;

      

}

app/Models/Master/AdminUnitTyp.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class AdminUnitTyp extends Model
{
    protected $table = 'admin_unit_typ';
    protected $guarded = [];
}

app/Models/Master/Company.php
<?php

namespace App\Models\Master;


use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'company';
    protected $guarded = [];

    public function strategic_plan(){
        return $this->hasMany(StrategicPlan::class,'company_id','id');

    }
}

app/Models/Master/DropAdminInCompView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class DropAdminInCompView extends Model
{
    protected $table = 'drop_admin_in_comp_view';
    protected $guarded = [];
}

app/Models/Master/EexecutiveTargetCompView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class EexecutiveTargetCompView extends Model
{
    protected $table = 'executive_target_comp_view';
    protected $guarded = [];
}

app/Models/Master/EmpAdminComp.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class EmpAdminComp extends Model
{
    protected $table = 'emp_admin_comp';
    protected $guarded = [];
}

app/Models/Master/EmpInActivity.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class EmpInActivity extends Model
{
    protected $table = 'emp_in_activity';
    protected $guarded = [];
}

app/Models/Master/Employee.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employee';
    protected $guarded = [];
}

app/Models/Master/ExecutiveTarget.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ExecutiveTarget extends Model
{
    protected $table = 'executive_target';
    protected $guarded = [];
}

app/Models/Master/ExecutiveTargetCompView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ExecutiveTargetCompView extends Model
{
    //
}

app/Models/Master/ExecutiveTargetNameView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ExecutiveTargetNameView extends Model
{
    protected $table = 'executive_target_name_view';
    protected $guarded = [];
}

resources/views/master/fundingsources/create.blade.php
@extends('layouts.app')
@section('content')
<div class="layout-px-spacing">
    <div class="row layout-top-spacing">

        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
            <div class="widget widget-one">
                <div class="widget-heading">
                    <nav class="breadcrumb-two" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">   </a></li>
                            <li class="breadcrumb-item"><a href="{{route('fundingsources.index')}}">  </a></li>
                            <li class="breadcrumb-item active"><a href="javascript:void(0);"> أضف   </a></li>
                            <li class="breadcrumb-item"></li>
                        </ol>
                    </nav>
                </div>

<br>




                <div class="widget-content widget-content-area">
                <form id="createForm" action="{{route('fundingsources.store')}}" method="POST">
               @csrf
                <table id="paymentTable" class="table table-bordered">

                <!-- <input type="hidden" value="{{Auth::user()->company_id}}" name="company_id"/> -->
                <input type="hidden" value="{{request()->input('executive_target_id')}}" name="executive_target_id" >

                    <thead>
                    <tr>
                        <th>  مصدر او جهه التمويل </th>
                        <th>قيمة التمويل</th>
                    <th>
                            <a id="aadd"><i class="fas fa-plus"></i></a>
                        </th>
                     
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <tr>
                            

                        <td>
                                <input type="text" class="form-control" name="fundingsources[0][funding_entity]" value="{{request()->input('funding_entity')}}"
                                 placeholder="  " autocomplete="off" >
                           </td>


                           

                            <td>
                            <input type="text" class="form-control"  name="fundingsources[0][funding_value]" value="{{request()->input('funding_value')}}"
                                 placeholder="  " autocomplete="off" >
                            </td>
                            <td>
                            </td>
                        </tr>
                    </tbody>
                </table>
                </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-primary mt-3">أضافة</button>
                    <a href="{{route('fundingsources.index',['executive_target_id'=>request()->input('executive_target_id')])}}" class="btn btn-danger mt-3">إلغاء / عودة</a>
                </div>
            </div>
        </form>
    </div>
</div>

        </div>
    </div>
</div>
@endsection
@push('scripts')

<script>
      $(document).ready(function(){
        $("#paymentTable").on("click", ".remove", function () {
        $(this).closest("tr").remove();
        });


        var counter  = 1;
      $("#aadd").click(function(){
        var tr = '<tr>'+
                '<td><input type="text" class="form-control" name="fundingsources['+counter+'][funding_entity]" value="{{request()->input('funding_entity')}}"></td>'+
                '<td><input type="text" class="form-control" name="fundingsources['+counter+'][funding_value]" value="{{request()->input('funding_value')}}"></td>'+
            '<td style="width:85px;"><button type="button" class="btn btn-danger remove"><i class="fa fa-trash"></i></button></td>'
            '</tr>';
            counter++;
            $('#paymentTable').append(tr);



            
        });
    });

</script>
 <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
@endpush

resources/views/master/fundingsources/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">

            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
                <div class="widget widget-one">
                    <div class="widget-heading">
                        <nav class="breadcrumb-two" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                {{-- <li class="breadcrumb-item"><a href="javascript:void(0);"> بيانات الحركة</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('fundingsources.index') }}"> تعديل </a></li>
                                <li class="breadcrumb-item active"><a href="javascript:void(0);"> تعديل  </a></li> --}}
                                <li class="breadcrumb-item"></li>
                            </ol>
                        </nav>
                    </div>
                    <div class="widget-content widget-content-area">
                        <form id="createForm" action="{{ route('fundingsources.update', ['fundingsource' => $fundingsource]) }}" method="POST">
                            @csrf
                            @method('put')
                            <div class="form-row">




                            <div class="form-group col-md-3">
                                    <label for="nameInput">   مصدر او جهة التمويل  </label>
                                     <input type="text" class="form-control" id="emailInput" name="funding_entity"
                                        value="{{ old('funding_entity',$fundingsource->funding_entity) }}" >

                                    @error('funding_entity')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>






                                <div class="form-group col-md-3">
                                    <label for="nameInput">   قيمة التمويل  </label>
                                     <input type="text" class="form-control"  name="funding_value"
                                        value="{{ old('funding_value',$fundingsource->funding_value) }}" >

                                    @error('funding_value')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                    
                      </div>
                       <div class="form-row">
                    
                      
                      </div>
                  
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary mt-3">تعديل</button>
                                    <a href="{{ route('fundingsources.index',['executive_target_id'=>request()->input('executive_target_id')])}}" class="btn btn-danger mt-3">إلغاء / عودة </a>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/master/fundingsources/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
                <div class="widget widget-one">
                    <div class="widget-heading">
                          <nav class="breadcrumb-two" aria-label="breadcrumb">
                            <ol class="breadcrumb">

                                  <li class="breadcrumb-item active"><a href="javascript:void(0);">     مصادر التمويل
                                        </a></li>
                                <li class="breadcrumb-item"></li>
                            </ol>
                        </nav>
                        @permission('Fundingsources-Create')
                            <div class="row">
                                <div class="col-md-12 text-right mb-5">
                                
                                    <a style="color:black !important; font-weight:bold;" href="{{ route('fundingsources.create',['executive_target_id'=>request()->input('executive_target_id')]) }}" class="btn btn-outline-success">أضف    </a>
                                 
                                </div>
                            </div>
                        @endpermission
                    </div>
          


                    <input value="{{Auth::user()->company_id}}" name="company_id" hidden/>



                    
                    <div class="widget-content widget-content-area">
                        <div class="table-responsive">
                            <table class="table table-success table-striped">
                                <thead>
                                    <tr>
                                        <!-- <th>م</th> -->
                                        <th>   مصدر او جهه التمويل </th>
                                        <th>  قيمة  التمويل </th>
                                         
                                        <th class='text-center' style='width:26px;'></th>

                                        <th class='text-left' style='width:26px;'>تعديل</th>
                                       
                                        <th class='text-center' style='width:26px;'>مسح</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($fundingsourcescompview as $item)
                                        <tr>

                                            <td>{{ $item->funding_entity}}</td>
                                             <td>{{ $item->funding_value}}</td>
                                            
                                        

                                             <td class="text-center">
                                                <ul class="table-controls">
                                                    @permission('Fundingsource-Edit')
                                                     <li>
                                                            <a href="{{ route('fundingsources.edit', ['fundingsource' => $item->id]) }}"
                                                                data-toggle="tooltip" data-placement="top" title=""
                                                                data-original-title="edit">
                                                                <i class="far fa-edit text-primary"></i>
                                                            </a>
                                                          
                                                        </li>
                                                    @endpermission
                                            </td>

                                             <td class="text-center">
                                                <ul class="table-controls">
                                                   
                                            </td>
                                        
                                            <td class="text-center">
                                                <ul class="table-controls">
                                                    @permission('Fundingsources-Delete')
                                                        
                                                <li>
                                                    <form action="{{route('fundingsources.destroy',['fundingsource'=>$item->id])}}" method="post">
                                                     @method('DELETE')
                                                     @csrf
                                                     <button style="border: none; background: none;" type="submit" class="fa fa-trash text-primary"></button>
                                                    </form>
                                                </li>
                                                    @endpermission

                                                </ul>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr class="text-center">
                                            <td colspan="7">{{ trans('home.no_data_found') }}</td>
                                        </tr>
                                    @endforelse

                                </tbody>

                            </table>
                        </div>
                        <div class="paginating-container">
                          
                            {{-- <a style="color:black !important; font-weight:bold;" href="" class="btn btn-outline-success">عــــــــودة </a> --}}

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection