routes/web.php
<?php

use App\Models\ViewModel\RootMenuNode;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    /*
    |-------------------------------------------
    | admin routes
    |--------------------------------------------
    */
    Route::prefix('admin')->namespace('Admin')->group(function () {
        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::get('profile', 'UserController@showProfile')->name('profile');

        Route::get('reset-password', 'ResetPasswordController@edit')->name('user.reset-password');
        Route::put('reset-password', 'ResetPasswordController@update');
    });
    /*
    |-------------------------------------------
    | master routes
    |--------------------------------------------
    */
    Route::prefix('master')->namespace('Master')->group(function () {
        Route::resource('company', 'CompanyController');
        Route::resource('activity', 'ActivityController');
        Route::resource('executivetarget', 'EexecutiveTargetController');
        Route::resource('empinactivity', 'EmpInActivityController');
        Route::resource('strategicplan', 'StrategicPlanController');
        Route::resource('employee', 'EmployeeController');
        Route::resource('adminunit', 'AdminUnitController');

        Route::resource('activityfollowup', 'ActivityFollowUpController');
        Route::resource('targetoutput', 'TargetOutputController');
        Route::resource('admininactivity', 'AdminInCompController');
        Route::resource('tasks', 'TasksController');
        Route::resource('planWeeks', 'MonthWeekController');

        Route::resource('fundingsources', 'FundingSourcesController');

        Route::resource('perfornanceindex', 'PerfornanceIndexController');
        Route::resource('strategictarget', 'StrategicTargetController');
        Route::resource('targetindex', 'TargetIndexController');
        Route::resource('follow', 'FollowActivityExeViewController');

    });
});
Auth::routes(['register' => false]);

app/Models/Master/Activity.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;
use Bitwise\PermissionSeeder\PermissionSeederContract;
use Bitwise\PermissionSeeder\Traits\PermissionSeederTrait;
use App\Traits\HasFilter;


class Activity extends Model implements PermissionSeederContract
{
    use HasFilter;
    protected $table = 'activity';
    protected $guarded = [];
    use PermissionSeederTrait;
    public function getPermissionActions(){
        return config('permission_seeder.actions',[
            'List',
            'Create',
            'Edit',
            'Delete'
        ]);
}
}

app/Models/Master/ActivityEmpAdminView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityEmpAdminView extends Model
{
    protected $table = 'activity_emp_admin_view';
    protected $guarded = [];

  
}

app/Models/Master/ActivityFollowExecutiveView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityFollowExecutiveView extends Model
{
    protected $table = 'activity_follow_executive_view';
    protected $guarded = [];
}

app/Models/Master/ActivityFollowPlanWeeksView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityFollowPlanWeeksView extends Model
{
    protected $table = 'activity_follow_up_plan_weeks_comp_view';
    protected $guarded = [];
}

app/Models/Master/ActivityFollowUp.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityFollowUp extends Model
{
    protected $table = 'activity_follow_up';
    protected $guarded = [];
}

app/Models/Master/ActivityFollowUpView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ActivityFollowUpView extends Model
{
    protected $table = 'activity_follow_up_view';
    protected $guarded = [];
}

app/Models/Master/AddFollowActiveView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class AddFollowActiveView extends Model
{
    protected $table = 'add_follow_active_view1';
    protected $guarded = [];
}

app/Models/Master/AddFollowActiveViewLast.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class AddFollowActiveViewLast extends Model
{
    protected $table = 'add_follow_active_view';
    protected $guarded = [];
}

app/Models/Master/AdminInActivity.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class AdminInActivity extends Model
{
    protected $table = 'admin_in_activity';
    protected $guarded = [];
}

app/Models/Master/AdminUnit.php
<?php

namespace App\Models\Master;
use Illuminate\Support\Facades\Auth;
use App\Traits\HasFilter;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Master\OperationPlane;

class AdminUnit extends Model

    {
        protected $table = 'admin_unit';
        protected $guarded = [];
        use HasFilter;

      

}

app/Models/Master/AdminUnitTyp.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class AdminUnitTyp extends Model
{
    protected $table = 'admin_unit_typ';
    protected $guarded = [];
}

app/Models/Master/Company.php
<?php

namespace App\Models\Master;


use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'company';
    protected $guarded = [];

    public function strategic_plan(){
        return $this->hasMany(StrategicPlan::class,'company_id','id');

    }
}

app/Models/Master/DropAdminInCompView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class DropAdminInCompView extends Model
{
    protected $table = 'drop_admin_in_comp_view';
    protected $guarded = [];
}

app/Models/Master/EexecutiveTargetCompView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class EexecutiveTargetCompView extends Model
{
    protected $table = 'executive_target_comp_view';
    protected $guarded = [];
}

app/Models/Master/EmpAdminComp.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class EmpAdminComp extends Model
{
    protected $table = 'emp_admin_comp';
    protected $guarded = [];
}

app/Models/Master/EmpInActivity.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class EmpInActivity extends Model
{
    protected $table = 'emp_in_activity';
    protected $guarded = [];
}

app/Models/Master/Employee.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employee';
    protected $guarded = [];
}

app/Models/Master/ExecutiveTarget.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ExecutiveTarget extends Model
{
    protected $table = 'executive_target';
    protected $guarded = [];
}

app/Models/Master/ExecutiveTargetCompView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ExecutiveTargetCompView extends Model
{
    //
}

app/Models/Master/ExecutiveTargetNameView.php
<?php

namespace App\models\master;

use Illuminate\Database\Eloquent\Model;

class ExecutiveTargetNameView extends Model
{
    protected $table = 'executive_target_name_view';
    protected $guarded = [];
}

resources/views/master/admininactivity/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
                <div class="widget widget-one">
                    <div class="widget-heading">
                        <nav class="breadcrumb-two" aria-label="breadcrumb">
                             <ol class="breadcrumb">
    
                                <li class="breadcrumb-item active"><a href="javascript:void(0);"> أضف    متابعة جديدة </a></li>
                                <li class="breadcrumb-item"></li>
                            </ol>
                        </nav>
                    </div>
                    <div class="widget-content widget-content-area">
                        <form id="createForm" action="{{ route('admininactivity.store') }}" method="POST">
                            @csrf
                            <input type="text" value="{{request()->input('activity_id')}}" name="activity_id" hidden>
                            <div class="form-row">
                                              <div class="form-group col-md-3">
                                    <label for="nameInput">     الوحدة الادارية </label>
                                         <select class=" form-control" id="stationNamesInput" data-live-search="true"
                                        name="admin_unit_id" data-size="10" title="">
                                        <option value="">اختر</option>
                                        @foreach ($dropadminincompview as $item)
                                            <option value="{{ $item->id }}"
                                                {{ $item->id == old('id') ? 'selected' : '' }}>{{ $item->name }}
                                            </option>
                                        @endforeach
                                    </select>

                                    @error('admin_unit_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                       </div>
                         <div class="form-row">
                         <div class="form-group col-md-3">
                                    <label for="nameInput">   تاريخ مخطط  بداية النشاط</label>
                                     <input type="date" class="form-control" id="emailInput" name="planned_from"
                                        value="{{ old('planned_from') }}" placeholder="  " autocomplete="off">

                                    @error('planned_from')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                     <div class="form-group col-md-3">
                                    <label for="nameInput">   تاريخ مخطط  نهاية النشاط</label>
                                     <input type="date" class="form-control" id="emailInput" name="planned_to"
                                        value="{{ old('planned_to') }}" placeholder="  " autocomplete="off">

                                    @error('planned_to')
                                        <div style="color:red">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>


                      </div>
                       <div class="form-row">
                       <div class="form-group col-md-3">

                                    <label for="nameInput">   تاريخ فعلى  لبداية النشاط</label>
                                     <input type="date" class="form-control" id="emailInput" name="actual_from"
                                        value="{{ old('actual_from') }}" placeholder=" الوحدة الادارية" autocomplete="off">

                                    @error('actual_from')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                     <div class="form-group col-md-3">

                                    <label for="nameInput">   تاريخ فعلى  لنهاية النشاط</label>
                                     <input type="date" class="form-control" id="emailInput" name="actual_to"
                                        value="{{ old('actual_to') }}" placeholder=" الوحدة الادارية" autocomplete="off">

                                    @error('actual_to')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                         </div>

                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <button type="submit" class="btn btn-primary mt-3">أضف</button>
                                        <a href="{{ route('admininactivity.index') }}" class="btn btn-danger mt-3">إلغاء / عودة
                                        </a>
                                    </div>
                                </div>




                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/master/admininactivity/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">

            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
                <div class="widget widget-one">
                    <div class="widget-heading">
                        <nav class="breadcrumb-two" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                             
                                <li class="breadcrumb-item"></li>
                            </ol>
                        </nav>
                    </div>
                    <div class="widget-content widget-content-area">
                        <form id="createForm" action="{{ route('admininactivity.update', ['admininactivity' => $admininactivity]) }}" method="POST">
                            @csrf
                            @method('put')
                             <input type="text" value="{{request()->input('activity_id')}}" name="activity_id" hidden>
                            <div class="form-row">
                     <div class="form-group col-md-3">
                                    <label for="nameInput">     الوحدة الادارية </label>
                                         <select class=" form-control" id="stationNamesInput" data-live-search="true"
                                        name="admin_unit_id" data-size="10" title="">
                                        <option value="">اختر</option>
                                        @foreach ($dropadminincompview as $item)
                                            <option value="{{ $item->admin_unit_id }}"
                                                {{ $item->admin_unit_id == old('admin_unit_id',$admininactivity->admin_unit_id) ? 'selected' : '' }}>{{ $item->admin_unit_name }}
                                            </option>
                                        @endforeach
                                    </select>

                                    @error('admin_unit_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                 </div>
                                    <div class="form-row">
                                           <div class="form-group col-md-3">
                                    <label for="nameInput">   تاريخ مخطط  بداية النشاط</label>
                                     <input type="date" class="form-control" id="emailInput" name="planned_from"
                                        value="{{ old('planned_from',$admininactivity->planned_from) }}" placeholder="  " autocomplete="off">

                                    @error('planned_from')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                     <div class="form-group col-md-3">
                                    <label for="nameInput">   تاريخ مخطط  نهاية النشاط</label>
                                     <input type="date" class="form-control" id="emailInput" name="planned_to"
                                        value="{{ old('planned_to',$admininactivity->planned_to) }}" placeholder="  " autocomplete="off">

                                    @error('planned_to')
                                        <div style="color:red">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>


                      </div>
                       <div class="form-row">
                       <div class="form-group col-md-3">

                                    <label for="nameInput">   تاريخ فعلى  لبداية النشاط</label>
                                     <input type="date" class="form-control" id="emailInput" name="actual_from"
                                        value="{{ old('actual_from',$admininactivity->actual_from) }}" placeholder=" الوحدة الادارية" autocomplete="off">

                                    @error('actual_from')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                     <div class="form-group col-md-3">

                                    <label for="nameInput">   تاريخ فعلى  لنهاية النشاط</label>
                                     <input type="date" class="form-control" id="emailInput" name="actual_to"
                                        value="{{ old('actual_to',$admininactivity->actual_to) }}" placeholder=" الوحدة الادارية" autocomplete="off">

                                    @error('actual_to')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                         </div>
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary mt-3">تعديل</button>
                                    <a href="{{ route('admininactivity.index') }}" class="btn btn-danger mt-3">إلغاء / عودة </a>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/master/admininactivity/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
                <div class="widget widget-one">
                    <div class="widget-heading">
                          <nav class="breadcrumb-two" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                  <li class="breadcrumb-item active"><a href="javascript:void(0);">  القطاع المشارك فى النشاط
                                        </a></li>
                                <li class="breadcrumb-item"></li>
                            </ol>
                        </nav>

                        @permission('AdminInActivity-Create')
                            <div class="row">
                                <div class="col-md-12 text-right mb-5">
                                     {{-- @if(Auth::user()->company_id > 45)
                                        @else --}}
                                    <a style="color:black !important; font-weight:bold;" href="{{ route('admininactivity.create',['activity_id'=>request()->input('activity_id')]) }}" class="btn btn-outline-success">أضف    </a>
                                      {{-- @endif --}}
                                </div>
                            </div>
                        @endpermission
                    </div>
                      {{-- <form action="{{ route('activity.index') }}">
                    <div class="form-row">

                                  <div class="form-group col-md-3">
                                    <label for="nameInput">  اسم  البـــنك</label>
                                      <select class=" form-control"  data-live-search="true"
                                name="name" data-size="10" title="ÃÎÊÑ">
                                <option value="">اختر</option>
                                @foreach ($bankName as $item)
                                    <option value="{{ $item->name }}"
                                        {{ $item->name == old('name',request()->input('name')) ? 'selected' : '' }}>{{ $item->name }}
                                    </option>
                                @endforeach
                            </select>
                                    @error('main_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>


                    </div>
                        <div class="col-md-8 text-center">
                        <button type="submit" class="btn btn-primary mt-3"> ابحث</button>
                            <a href="{{route('Bank.index') }}" class="btn btn-danger mt-3">الغاء
                            </a>
                    </div>
                    </div>
                    </form> --}}
                    <div class="widget-content widget-content-area">
                        <div class="table-responsive">
                              <table class="table table table-striped">
                                <thead>
                                    <tr>

                                         <th>   كود القطاع</th>
                                        <th>     اسم القطاع </th>
                                        <th class='text-center' style='width:26px;'>تعديل</th>
                                        <th class='text-center' style='width:26px;'>مسح</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($dropadminincompview as $item)
                                        <tr class="table-secondary">


                                             <td>{{ $item->admin_unit_id}}</td>
                                              <td>{{ $item->admin_unit_name}}</td>
                                            <td class="text-center">
                                                <ul class="table-controls">
                                                    @permission('AdminInActivity-Edit')
                                                     <li>
                                                            <a href="{{ route('admininactivity.edit', ['admininactivity' => $item->id,'activity_id'=>request()->input('activity_id')]) }}"
                                                                data-toggle="tooltip" data-placement="top" title=""
                                                                data-original-title="edit">
                                                                <i class="far fa-edit text-primary"></i>
                                                            </a>
                                                            {{-- @endif --}}
                                                        </li>
                                                    @endpermission
                                            </td>
{{--
                                            @if(Auth::user()->company_id > 45)
                                            @else --}}
                                            <td class="text-center">
                                                <ul class="table-controls">
                                                    @permission('AdminInActivity-Delete')
                                                        <li>
                                                            <form
                                                                action="{{ route('admininactivity.destroy', ['admininactivity' => $item->id]) }}"
                                                                method="post">
                                                                @method('DELETE')
                                                                @csrf
                                                                <button type="submit" class="fa fa-trash text-primary"></button>
                                                            </form>
                                           {{-- @endif --}}
                                                        </li>
                                                    @endpermission

                                                </ul>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr class="text-center">
                                            <td colspan="7">{{ trans('home.no_data_found') }}</td>
                                        </tr>
                                    @endforelse

                                </tbody>

                            </table>
                        </div>
                        <div class="paginating-container">
                            {{ $dropadminincompview->links() }}
                            {{-- <a style="color:black !important; font-weight:bold;" href="" class="btn btn-outline-success">عــــــــودة </a> --}}

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection